version: "3.8"

services:
  service-event:
    image: rabbitmq:3.8.13-management
    container_name: component-event
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
    - 5672:5672
    - 15672:15672
    networks:
    - projectBase-cpn-ti  

networks:
  projectBase-cpn-ti:
    name: micro-net